"use client";
import {AlertTriangle, Bell, CheckCircle2, ChevronRight, FileText, LayoutDashboard, Menu, Pill, Search, Settings, Sparkles, UserRound} from "lucide-react";
import {useMemo,useState} from "react";
import {demoCases} from "./medication-cases";
import styles from "./MedVerifyApp.module.css";

const statusLabel={MATCH:"Matched",REVIEW:"Review",MISMATCH:"Mismatch"} as const;
type Result="MATCH"|"REVIEW"|"MISMATCH";
type Patient={id:string;name:string;mrn:string;hn:string;sex:string;dob:string;ward:string;bed:string;generated:string;medications:(typeof demoCases)[number][]};
const patients:Patient[]=[
 {id:"P001",name:"CHAN Tai Man",mrn:"MRN-100238",hn:"HN-310482-1",sex:"Male",dob:"22 Jan 1949",ward:"8A",bed:"03",generated:"18 min ago",medications:[demoCases[0],demoCases[11],demoCases[22],demoCases[3],demoCases[14],demoCases[25]]},
 {id:"P002",name:"LEE Mei Ling",mrn:"MRN-104891",hn:"HN-284019-4",sex:"Female",dob:"08 Sep 1966",ward:"8A",bed:"07",generated:"32 min ago",medications:[demoCases[16],demoCases[7],demoCases[18],demoCases[9],demoCases[0]]},
 {id:"P003",name:"WONG Ka Wai",mrn:"MRN-109472",hn:"HN-204981-7",sex:"Male",dob:"14 Mar 1958",ward:"8A",bed:"12",generated:"2 h ago",medications:[demoCases[20],demoCases[1],demoCases[12],demoCases[23],demoCases[4],demoCases[15]]},
 {id:"P004",name:"LAM Siu Ming",mrn:"MRN-112605",hn:"HN-390156-2",sex:"Male",dob:"30 Nov 1974",ward:"8B",bed:"02",generated:"48 min ago",medications:[demoCases[2],demoCases[13],demoCases[14],demoCases[5]]},
 {id:"P005",name:"HO Wing Yan",mrn:"MRN-118033",hn:"HN-401873-5",sex:"Female",dob:"19 Jun 1981",ward:"8B",bed:"09",generated:"1 h ago",medications:[demoCases[26],demoCases[7],demoCases[18],demoCases[29],demoCases[0]]},
 {id:"P006",name:"CHEUNG Pui Shan",mrn:"MRN-120984",hn:"HN-448210-8",sex:"Female",dob:"03 Feb 1992",ward:"9A",bed:"16",generated:"12 min ago",medications:[demoCases[6],demoCases[7],demoCases[8],demoCases[9]]}
];
function patientStatus(p:Patient):Result{return p.medications.some(m=>m.comparison.overallResult==="MISMATCH")?"MISMATCH":p.medications.some(m=>m.comparison.overallResult==="REVIEW")?"REVIEW":"MATCH"}

export default function MedVerifyApp(){
 const [selected,setSelected]=useState(patients[2]);
 const [query,setQuery]=useState("");
 const [actions,setActions]=useState<Record<string,"ack"|"escalate">>({});
 const [view,setView]=useState<"overview"|"dashboard"|"doctor"|"pharmacy"|"rules">("overview");
 const [runs,setRuns]=useState<Record<string,number>>({});
 const filtered=useMemo(()=>patients.filter(p=>`${p.name} ${p.mrn} ${p.hn}`.toLowerCase().includes(query.toLowerCase())),[query]);
 const recordAction=(medId:string,value:"ack"|"escalate")=>setActions(a=>({...a,[`${selected.id}-${medId}`]:value}));
 return <div className={styles.shell}>
  <header className={styles.topbar}><button aria-label="Menu"><Menu/></button><button className={styles.brand} onClick={()=>setView("overview")}><span>∿</span>MedVerify</button><label className={styles.search}><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search patient name or MRN…"/></label><nav className={styles.roleNav}><button aria-pressed={view==="overview"} onClick={()=>setView("overview")}>Dashboard</button><button aria-pressed={view==="doctor"} onClick={()=>setView("doctor")}>Doctor</button><button aria-pressed={view==="pharmacy"} onClick={()=>setView("pharmacy")}>Pharmacy</button><button aria-pressed={view==="dashboard"} onClick={()=>setView("dashboard")}>Nurse</button></nav><button className={styles.rulesButton} aria-pressed={view==="rules"} onClick={()=>setView("rules")}><Settings/>Rules</button><button className={styles.bell} aria-label="Notifications"><Bell/><i/></button><div className={styles.user}><b>{view==="doctor"?"DL":view==="pharmacy"?"PT":"SC"}</b><span><strong>{view==="doctor"?"Dr. Leung K.H.":view==="pharmacy"?"Pharmacist T. Ng":"Nurse S. Cheung"}</strong><small>{view==="doctor"?"Medical team":view==="pharmacy"?"Pharmacy review":"Ward 8A · RN"}</small></span></div></header>
  {view==="rules"?<RulesSettings/>:view==="overview"?<OverviewDashboard onNavigate={setView}/>:view==="doctor"?<DoctorWorkspace runs={runs} onRun={key=>setRuns(r=>({...r,[key]:(r[key]||0)+1}))}/>:view==="pharmacy"?<PharmacyWorkspace/>:
  <div className={styles.layout}>
   <aside className={styles.sidebar}><div className={styles.sideTitle}><span>Matched alerts</span><b>{patients.length}</b></div>{filtered.map(p=>{const pending=p.medications.filter(m=>m.comparison.overallResult==="MATCH").length;return <button key={p.id} className={selected.id===p.id?styles.active:""} onClick={()=>setSelected(p)}><div><strong>{p.name}</strong><small>{p.mrn} · {pending} pending</small></div><span data-state="MATCH">{pending} matched</span><ChevronRight/></button>})}</aside>
   <main className={styles.main}>
    <div className={styles.crumb}>Patient alerts <ChevronRight/> {selected.id}</div>
    <section className={styles.patient}><div className={styles.avatar}><UserRound/></div><div><h1>{selected.name}</h1><p>{selected.mrn} · {selected.hn} · {selected.sex} · DOB {selected.dob}</p><small>Ward {selected.ward} · Bed {selected.bed}</small></div><span className={styles.pendingBadge}>Pending nurse acknowledgement</span></section>
    <section className={styles.meta}>{[["Alert ID",`ALR-${selected.id}-248`],["Matched medications",String(selected.medications.filter(m=>m.comparison.overallResult==="MATCH").length)],["Workflow","n8n comparison complete"],["Generated",selected.generated]].map(([a,b])=><div key={a}><span>{a}</span><b>{b}</b></div>)}</section>
    <div className={styles.sectionTitle}><h2>Matched medications pending acknowledgement</h2><Status state="MATCH"/></div>
    {selected.medications.filter(m=>m.comparison.overallResult==="MATCH").map((med,i)=>{const key=`${selected.id}-${med.id}`,action=actions[key];return <MedicationCard key={key} selected={med} number={i+1} action={action} onAction={v=>recordAction(med.id,v)}/>})}
    <section className={styles.audit}><h2>Audit trail</h2><div><i/><span><b>Comparison generated</b><small>System · Automated<br/>{selected.generated}</small></span></div>{Object.entries(actions).filter(([k])=>k.startsWith(`${selected.id}-`)).map(([k,value])=>{const med=selected.medications.find(m=>k.endsWith(m.id));return <div key={k}><i/><span><b>{med?.title}: {value==="ack"?"comparison acknowledged":"review escalation created"}</b><small>Nurse S. Cheung · just now</small></span></div>})}</section>
   </main>
  </div>}
 </div>
}

function Status({state}:{state:"MATCH"|"REVIEW"|"MISMATCH"}){return <span className={styles.status} data-state={state}>{state==="MATCH"?<CheckCircle2/>:<AlertTriangle/>}{statusLabel[state]}</span>}
function MedicationCard({selected,number,action,onAction}:{selected:typeof demoCases[number];number:number;action?:"ack"|"escalate";onAction:(v:"ack"|"escalate")=>void}){return <article className={styles.medCard}><header><div><h3>{number}. {selected.title}</h3><small>Medication order · {selected.id}</small></div><Status state={selected.comparison.overallResult}/></header><div className={styles.sources}><Source name="E-DOCUMENTATION" r={selected.eDocumentation}/><Source name="IPMOE" r={selected.ipmoe}/></div><div className={styles.ai}><Sparkles/><div><b>AI EXPLANATION</b><p>{selected.comparison.message} {selected.comparison.fields.find(f=>f.result!=="MATCH")?.explanation}</p></div></div><div className={styles.medActions}><p>Record that you reviewed this medication comparison. This is not medication approval.</p><div><button className={styles.ack} onClick={()=>onAction("ack")}><CheckCircle2/>{action==="ack"?"Acknowledged":"Acknowledge"}</button><button className={styles.escalate} onClick={()=>onAction("escalate")}><AlertTriangle/>{action==="escalate"?"Escalated":"Escalate"}</button></div>{action&&<small data-action={action}>{action==="ack"?"Acknowledgement recorded in audit trail.":"Escalation sent for clinical review."}</small>}</div></article>}
function Source({name,r}:{name:string;r:any}){return <section className={styles.source}><header><FileText/><b>{name}</b><span>◷ 2 h ago</span></header><h4>{r.medicationName}</h4><dl>{[["Dose",r.doseValue==null?"Not supplied":`${r.doseValue} ${r.doseUnit}`],["Route",r.route||"Not supplied"],["Frequency",r.intervalMinutes?`Every ${r.intervalMinutes/60} hours`:r.scheduledTime||"Review"],["PRN",r.specialInstructions==="PRN"?"Yes":"No"],["Duration",r.isIntravenousFluid?`${r.infusionDurationMinutes||"—"} minutes`:"Ongoing"],["Special instructions",r.specialInstructions||"—"]].map(([a,b])=><div key={a}><dt>{a}</dt><dd>{b}</dd></div>)}</dl><footer>♧ Dr. Leung K.H. · {name==="IPMOE"?"IPMOE":"e-Documentation"}</footer></section>}

function OverviewDashboard({onNavigate}:{onNavigate:(view:"dashboard"|"doctor"|"pharmacy")=>void}){
 const all=patients.flatMap(p=>p.medications),matched=all.filter(m=>m.comparison.overallResult==="MATCH").length,review=all.filter(m=>m.comparison.overallResult==="REVIEW").length,mismatch=all.filter(m=>m.comparison.overallResult==="MISMATCH").length;
 return <main className={styles.overview}><div className={styles.overviewHead}><div><p>Medication consistency verification</p><h1>Clinical workflow dashboard</h1><span>Demo overview · Synthetic data only</span></div><div><i/>n8n workflow operational</div></div><section className={styles.kpis}>{[[patients.length,"Patients with active workflows","teal"],[matched,"Matched · nurse acknowledgement","green"],[review,"Further review required","amber"],[mismatch,"Mismatch · amendment required","red"]].map(([n,l,c])=><article key={String(l)} data-colour={c}><span>{l}</span><b>{n}</b><small>Current synthetic queue</small></article>)}</section><section className={styles.overviewGrid}><article className={styles.flowCard}><h2>End-to-end workflow</h2><p>Current routing logic across clinical roles.</p><div className={styles.bigFlow}>{[["Doctor","Arrange and confirm medication"],["n8n","Compare e-Documentation and IPMOE"],["Route","Match → Nurse · Exception → Doctor/Pharmacy"],["Close","Acknowledge or amend with audit trail"]].map(([a,b],i)=><div key={a}><strong>{i+1}</strong><span><b>{a}</b><small>{b}</small></span>{i<3&&<ChevronRight/>}</div>)}</div></article><article className={styles.queueCard}><h2>Role queues</h2><p>Select a workspace to play through the product demo.</p><button onClick={()=>onNavigate("doctor")}><UserRound/><span><b>Doctor workspace</b><small>{review+mismatch} exceptions require review or amendment</small></span><ChevronRight/></button><button onClick={()=>onNavigate("pharmacy")}><Pill/><span><b>Pharmacy review</b><small>{review+mismatch} clinical consistency exceptions available</small></span><ChevronRight/></button><button onClick={()=>onNavigate("dashboard")}><Bell/><span><b>Nurse dashboard</b><small>{matched} matched medications pending acknowledgement</small></span><ChevronRight/></button></article></section><section className={styles.activity}><h2>Recent workflow activity</h2>{patients.slice(0,5).map((p,i)=><div key={p.id}><i data-state={i%3===0?"MATCH":i%3===1?"REVIEW":"MISMATCH"}/><span><b>{p.name}</b><small>{p.hn} · automated comparison completed</small></span><time>{p.generated}</time></div>)}</section></main>
}

function PharmacyWorkspace(){
 const queue=patients.flatMap(p=>p.medications.filter(m=>m.comparison.overallResult!=="MATCH").map(m=>({patient:p,med:m}))),[selected,setSelected]=useState(queue[0]),[note,setNote]=useState(""),[sent,setSent]=useState<Record<string,boolean>>({});
 const key=`${selected.patient.id}-${selected.med.id}`;
 return <div className={styles.pharmacyLayout}><aside className={styles.sidebar}><div className={styles.sideTitle}><span>Pharmacy review</span><b>{queue.length}</b></div>{queue.map(item=><button key={`${item.patient.id}-${item.med.id}`} className={key===`${item.patient.id}-${item.med.id}`?styles.active:""} onClick={()=>{setSelected(item);setNote("")}}><div><strong>{item.med.title}</strong><small>{item.patient.name} · {item.patient.hn}</small></div><span data-state={item.med.comparison.overallResult}>{statusLabel[item.med.comparison.overallResult]}</span><ChevronRight/></button>)}</aside><main className={styles.main}><div className={styles.crumb}>Pharmacy review <ChevronRight/> {selected.patient.name}</div><section className={styles.patient}><div className={styles.avatar}><Pill/></div><div><h1>{selected.med.title}</h1><p>{selected.patient.name} · {selected.patient.mrn} · {selected.patient.hn}</p><small>Ward {selected.patient.ward} · Bed {selected.patient.bed}</small></div><Status state={selected.med.comparison.overallResult}/></section><div className={styles.pharmacyNotice}><Pill/><div><b>Pharmacist review-only view</b><p>Review consistency information and send a recommendation to the prescriber. Medication orders cannot be approved or changed here.</p></div></div><article className={styles.medCard}><header><div><h3>Source comparison</h3><small>{selected.med.id} · n8n comparison complete</small></div><Status state={selected.med.comparison.overallResult}/></header><div className={styles.sources}><Source name="E-DOCUMENTATION" r={selected.med.eDocumentation}/><Source name="IPMOE" r={selected.med.ipmoe}/></div><div className={styles.ai}><Sparkles/><div><b>AI EXPLANATION</b><p>{selected.med.comparison.message} {selected.med.comparison.fields.find(f=>f.result!=="MATCH")?.explanation}</p></div></div><div className={styles.pharmacyAction}><label>Pharmacy recommendation<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Add recommendation for the prescribing doctor…"/></label><button onClick={()=>setSent(s=>({...s,[key]:true}))}>Send recommendation to doctor</button>{sent[key]&&<small>Recommendation sent to the doctor amendment queue and recorded in the audit trail.</small>}</div></article><section className={styles.audit}><h2>Audit trail</h2><div><i/><span><b>Exception routed to pharmacy review</b><small>n8n · Automated · {selected.patient.generated}</small></span></div>{sent[key]&&<div><i/><span><b>Pharmacy recommendation sent</b><small>Pharmacist T. Ng · just now</small></span></div>}</section></main></div>
}

function DoctorWorkspace({runs,onRun}:{runs:Record<string,number>;onRun:(key:string)=>void}){
 const [patient,setPatient]=useState(patients[0]);
 return <div className={styles.doctorLayout}><aside className={styles.sidebar}><div className={styles.sideTitle}><span>Doctor amendment queue</span><b>{patients.length}</b></div>{patients.map(p=><button key={p.id} className={patient.id===p.id?styles.active:""} onClick={()=>setPatient(p)}><div><strong>{p.name}</strong><small>{p.hn} · Ward {p.ward}</small></div><span data-state={patientStatus(p)}>{statusLabel[patientStatus(p)]}</span><ChevronRight/></button>)}</aside><main className={styles.main}>
  <div className={styles.crumb}>Doctor workspace <ChevronRight/> Medication orders</div>
  <section className={styles.patient}><div className={styles.avatar}><UserRound/></div><div><h1>{patient.name}</h1><p>{patient.mrn} · {patient.hn} · {patient.sex} · DOB {patient.dob}</p><small>Ward {patient.ward} · Bed {patient.bed}</small></div><span className={styles.doctorBadge}>Prescriber workflow</span></section>
  <section className={styles.workflowStrip}><b>Demo flow</b><span>1. Arrange medication</span><ChevronRight/><span>2. Doctor confirms</span><ChevronRight/><span>3. n8n compares</span><ChevronRight/><span>4. Route result</span></section>
  <div className={styles.sectionTitle}><h2>Medication orders</h2><span>{patient.medications.length} orders</span></div>
  {patient.medications.map((med,i)=>{const key=`${patient.id}-${med.id}`,ran=Boolean(runs[key]);return <article className={styles.doctorOrder} key={key}><header><div><h3>{i+1}. {med.title}</h3><small>Prepared in e-Documentation and IPMOE</small></div>{ran&&<Status state={med.comparison.overallResult}/>}</header><div className={styles.orderSummary}><span><small>Dose</small><b>{med.eDocumentation.doseValue} {med.eDocumentation.doseUnit}</b></span><span><small>Route</small><b>{med.eDocumentation.route}</b></span><span><small>Frequency</small><b>{med.eDocumentation.intervalMinutes?`Every ${med.eDocumentation.intervalMinutes/60} hours`:"Review"}</b></span><span><small>PRN</small><b>{med.eDocumentation.specialInstructions==="PRN"?"Yes":"No"}</b></span></div><button className={styles.confirmOrder} onClick={()=>onRun(key)}><CheckCircle2/>{ran?"Re-run n8n comparison":"Confirm & run n8n comparison"}</button>{ran&&<div className={styles.routeResult} data-state={med.comparison.overallResult}><Sparkles/><div><b>n8n comparison complete</b><p>{med.comparison.overallResult==="MATCH"?"Matched. Nurse alert created and sent to the clinical dashboard for acknowledgement.":med.comparison.overallResult==="REVIEW"?"Further review required. Automatically returned to the doctor amendment queue.":"Mismatch detected. Automatically escalated to the doctor for amendment."}</p></div></div>}</article>})}
 </main></div>
}

function RulesSettings(){
 const [normalise,setNormalise]=useState(true),[strictRoute,setStrictRoute]=useState(true),[explain,setExplain]=useState(true),[threshold,setThreshold]=useState(85);
 return <main className={styles.settingsPage}><div className={styles.settingsHead}><div><h1>Rules &amp; settings</h1><p>Prototype configuration for how comparisons are generated and flagged.</p></div><span>Prototype · Nursing Informatics access</span></div><div className={styles.settingsGrid}>
  <section className={styles.settingsCard}><h2>Matching rules</h2><p>How the system compares records across systems.</p><Toggle label="Normalize terminology" text="Treat PO = Oral, BD = twice daily, 1 g = 1000 mg, etc." on={normalise} set={setNormalise}/><Toggle label="Strict route matching" text="IV, IM, SC and PO must match exactly to be considered a match." on={strictRoute} set={setStrictRoute}/><Toggle label="AI explanation panel" text="Show a plain-language summary for each discrepancy." on={explain} set={setExplain}/></section>
  <section className={styles.settingsCard}><h2>Alert thresholds</h2><p>Controls when a partial match becomes an alert.</p><div className={styles.rangeLabel}><b>Match confidence threshold</b><strong>{threshold}%</strong></div><input className={styles.range} type="range" min="50" max="100" value={threshold} onChange={e=>setThreshold(Number(e.target.value))}/><small>Comparisons below this score are surfaced as alerts for review.</small></section>
  <section className={styles.settingsCard}><h2>Risk categories</h2><p>High-alert drug classes get elevated severity.</p><div className={styles.risks}>{["Anticoagulants","Insulin","Opioids","Chemotherapy","Concentrated electrolytes","Neuromuscular blockers"].map(x=><button key={x}>{x}</button>)}</div></section>
  <section className={styles.settingsCard}><h2>Terminology mapping</h2><p>Examples of equivalent expressions treated as a match.</p><table><thead><tr><th>Short form</th><th>Long form</th></tr></thead><tbody>{[["PO","Oral"],["BD / BID","Twice daily"],["TDS / TID","Three times daily"],["Q6H","Every 6 hours"],["Nocte","At night"],["SC","Subcutaneous"],["1 g","1000 mg"]].map(r=><tr key={r[0]}><th>{r[0]}</th><td>{r[1]}</td></tr>)}</tbody></table></section>
  <section className={styles.settingsCard}><h2>User roles</h2><p>Example role permissions in this prototype.</p><div className={styles.roles}>{[["Registered Nurse","Review, acknowledge, escalate alerts"],["Nursing Informatics","All nurse permissions + configure matching rules"],["Medication Safety Officer","All permissions + view audit reports"],["Pharmacist (review only)","Review comparison and escalation details"]].map(([a,b])=><article key={a}><b>{a}</b><small>{b}</small></article>)}</div></section>
  <section className={styles.settingsCard}><h2>Governance</h2><p>Configuration changes require approved ownership.</p><dl className={styles.governance}><div><dt>Rule set</dt><dd>MCV prototype v0.1</dd></div><div><dt>Last reviewed</dt><dd>Not clinically approved</dd></div><div><dt>Change control</dt><dd>Dual approval required</dd></div><div><dt>Audit logging</dt><dd>Enabled in prototype</dd></div></dl><button className={styles.saveRules}>Save prototype settings</button></section>
 </div></main>
}
function Toggle({label,text,on,set}:{label:string;text:string;on:boolean;set:(v:boolean)=>void}){return <div className={styles.toggleRow}><span><b>{label}</b><small>{text}</small></span><button role="switch" aria-checked={on} onClick={()=>set(!on)}><i/></button></div>}
